# Generated by Django 3.2.7 on 2022-01-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220117_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phnum', models.IntegerField(default=0)),
                ('url', models.CharField(default='', max_length=50)),
                ('is_costumer', models.BooleanField(default='No_costumer')),
                ('suggestion', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
