# Generated by Django 3.2.7 on 2022-01-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phnum',
            new_name='phone',
        ),
    ]
