# Generated by Django 3.2.7 on 2022-01-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_phnum_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_costumer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
